server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**, /warehouse/**, /products/**, /category/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/